# Brian, zombie rarisimo con lentes de sol (version nuestra del de Actions & Stuff): 1 de cada 1000.
# Juntado con las reglas de Fresh Animations Extensions (Dave), que siguen igual.
skins.1=2
name.1=iregex:Dave
skins.2=3
name.2=iregex:(brian|glare)
skins.3=1 2 3
weights.3=989 10 1
