# Globos (idea de Actions & Stuff): un happy ghast o su cria con estas etiquetas se ve como globo.
textures.1=2
name.1=iregex:(creeper balloon|globo creeper)
textures.2=3
name.2=iregex:(enderman balloon|globo enderman)
textures.3=4
name.3=iregex:(pig balloon|globo cerdo|globo chancho)
textures.4=5
name.4=iregex:(pumpkin balloon|globo calabaza|globo zapallo)
