# Sin arnes (idea de Actions & Stuff): no se ve el arnes, pero se puede montar igual.
models.2=2
name.2=iregex:(saddleless|sin arn.s|sin montura)
# Arnes celeste: alas de allay. Arnes negro: alas de dragon.
models.3=3
nbt.3.equipment.body.id=minecraft:light_blue_harness
models.4=4
nbt.4.equipment.body.id=minecraft:black_harness
