# Globos (idea de Actions & Stuff): un happy ghast o su cria con estas etiquetas se ve como globo.
models.2=2
name.2=iregex:(creeper balloon|globo creeper|enderman balloon|globo enderman|pig balloon|globo cerdo|globo chancho|pumpkin balloon|globo calabaza|globo zapallo)
